# Generated by Django 4.2 on 2024-01-09 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contact'),
        ('core', '0004_order'),
    ]

    operations = [
    ]
