# Generated by Django 4.2 on 2024-02-03 07:52

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ticket_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUpCode',
            fields=[
                ('ref_code', models.CharField(default=shortuuid.main.ShortUUID.random, editable=False, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('exp_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
