# Generated by Django 4.2 on 2024-02-03 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_topupcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='topupcode',
            name='ref_code',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='TopUpTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('top_up_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.topupcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
