# Generated by Django 4.2 on 2024-02-03 08:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_balance_alter_topupcode_ref_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topupcode',
            name='ref_code',
            field=models.CharField(default=core.models.generate_ref_code, editable=False, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
